name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12 # Or the latest version

  flutter_dotenv: ^5.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Add these dependencies for your college app
  provider: ^6.0.5

  # Updated http to a newer version that is compatible with flutter_polyline_points
  http: ^1.1.0

  # This package handles decoding the polyline from the directions API
  flutter_polyline_points: ^2.0.0

  file_picker: ^8.0.0+1
  badges: ^3.1.2  # Add this package
  geolocator: ^14.0.2   # add this

  # Removed the 'google_maps_webservice' package as it was causing a version conflict
  # with the http package. Your code can directly use the 'http' package to get directions.

  location: ^5.0.0      # For getting device location
  socket_io_client: ^2.0.3 # For real-time communication with the backend
  google_maps_flutter: ^2.6.0 # ✅ Update this line

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/img.png
    - assets/.env